### ISSUE TITLE
Java, I need please. 

### ISSUE THREAD

**Issue by Mustyashamma** [RyosukeMiyahara/JAVA_TRAINING#1]
I need help regarding this question please: Write a program that will sum the digits of a number. For example if
the number is 124, then the sum of its digits is 7 = 1+2+4

**Comment by RyosukeMiyahara** [comment]
Hi, thank you for asking. 
How about this way?
```
class Playground {
    public static void main(String[ ] args) {
        System.out.println(124/100 + (124-124/100*100)/10 + (124 - 124/10*10)/1);
    }
}
```
This code shows 7. 
Using this way and `String.valueOf(num).length()` , I guess we can write code.

**Comment by Zizu22** [comment]
hi, thanks for asking
I made this code in which u can input any no. and it will sum up the digits. But, it is valid for 1-5 digits only.
public class problem1 {

	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		System.out.println("Enter the no.");
		int n=sc.nextInt();
		int a=n/10;
		int sum=n-a*10;
		if(n<=10){
			sum=sum+a;
			System.out.println(sum);
			System.exit(0);
		}
		
		int b=a/10;
		sum=sum+a-b*10;
		
		if(b<=10){
		sum=sum+b;
		System.out.println(sum);
		System.exit(0);
		}
		
		int c=b/10;
		sum=sum+b-c*10;
		
		if(c<=10){
		sum=sum+c;
		System.out.println(sum);
		System.exit(0);
		}
		int d=c/10;
		sum=sum+c-d*10;
		sum=sum+d;
		
		System.out.println(sum);
		

	}

**Comment by Mustyashamma** [comment]
Thanks @z

**Comment by Mustyashamma** [comment]
Thanks @RyosukeMiyahara and @Zizu22

**Comment by RyosukeMiyahara** [comment]
@Mustyashamma If you are OK, could you please close this issue? Or do you need more help?

**Comment by Zizu22** [comment]
@Mustyashamma  Same
